# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
error_symbol = "[✘ ❯](bold red)" 
success_symbol = "[✔ ❯](bold green)" 
vicmd_symbol = "[v ❯](bold blue)"   
 
[package]
disabled = true

[directory]
read_only = " 🔒"
truncation_length = 4
style = "bold dimmed cyan"

#[hostname]
#ssh_only = false
#format =  "[$hostname](bold dimmed blue) "
#trim_at = ".companyname.com"
#disabled = false 

